### ISSUE TITLE
No database (server) found when creating a new database project

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#101]
When creating a new EF Core project for a service, there is no database (server) available.
Therefore the connection string etc is not correctly generated.
![image](https://user-images.githubusercontent.com/114572200/213244888-586e7327-72db-4713-906c-7c12ad6e9a69.png)

**Comment by GFlisch** [comment]
Fix in 2022.2.1.13
