### ISSUE TITLE
Small typo in log information program.cs : "Shutdown" instead of "Shut down"

### ISSUE THREAD

**Issue by GFlexi** [GFlisch/Arc4u.Guidance.Doc#107]
The correct spelling should be "Shutdown".
When we will look in logging to identify whether a service is up or not, we will naturally look for 'Shutdown'

```
finally
{
    Log.Information("Shut down complete");
    Log.CloseAndFlush();
}
```

vs

finally
{
    Log.Information("Shutdown complete");
    Log.CloseAndFlush();
}

**Comment by GFlisch** [comment]
Hi @GFlexi ,

Thanks. Will be fixed in the next version: 2022.2.12.
