### ISSUE TITLE
CSP for VueJS is not available yet

### ISSUE THREAD

**Issue by MarcMalek** [GFlisch/Arc4u.Guidance.Doc#117]
The integration of security-audit related recommandations within the Guidance has resulted in adding CSP code to Blazor applications. What do we do with the current VueJS applications which are deployed in PROD and on DMZ, are there some Guidance rules with state how to update them? And apart from adding CSP to secure applications, it would be practical to have the same way of working amongst different VueJS applications.

**Comment by GFlisch** [comment]
As the Guidance 2022 doesn't support VueJS this will not be implemented. I propose to take the code generated by the Guidance for a core service and configure the Csp manually.
