### ISSUE TITLE
YARP reverseproxy.json timeout configuration generated by Guidance is incorrect.

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#118]
Currently, we have something like this generated by default by the Guidance:

~~~json
        "HttpClient": {
          "MaxConnectionsPerServer": 16,
          "Timeout": "00:10:00"
        },
~~~

The `Timeout` has no effect: it's not part of the `HttpClient` configuration.
So it stays the default of 100 seconds, regardless which timeout setting you apply to your HttpClient.

To correct this, remove the `Timeout` property from the `HttpClient` and use the `ActivityTimeout` in `HttpRequest` like this:

~~~json
        "HttpClient": {
          "MaxConnectionsPerServer": 16,
        },
        "HttpRequest": {
          "Version": "2.0",
          "VersionPolicy": "RequestVersionOrHigher",
          "ActivityTimeout": "00:10:00"
        },
~~~

Reference: https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest

**Comment by GFlisch** [comment]
Implemented in the next version
