### ISSUE TITLE
Encrypt all secrets

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#12]
We need to encrypt all secrets being defined, that means within
 - appsettings
  - e.g. ClientSecret for ADFS authorization
 - database
 - in code (well if there should be something like that at all)

This is not only about secrets being used / defined by the project team, but also or especially concerning secrets being used by the arc4u framework.

**Comment by vvdb-architecture** [comment]
Somewhat related to https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/27

**Comment by rdarko** [comment]
This story is a blocker for working with off-grid devices

**Comment by rdarko** [comment]
Reminder to check: is there an option to use key vault instead of encrypting?

**Comment by GFlisch** [comment]
An implementation exists to support this in the branch [ConfigSecretProvider](https://github.com/GFlisch/Arc4u/tree/feature/ConfigSecretProvider). 
The doc in code is closed to be done (but still some comments to add.
The doc how to use this is to be done.
@vvdb-architecture, can you give your opinion on the implementatio?
