### ISSUE TITLE
mismatch 'configs/appsettings.json' but folder with Upper case

### ISSUE THREAD

**Issue by khalidEssouidi** [GFlisch/Arc4u.Guidance.Doc#120]
The guidance generate config path with a lower case 'configs/appsettings.json' but the folder is with Upper.
It has no impact in windows configuration but when we deploy host in a linux ubuntu pod, the config are not found

**Comment by GFlisch** [comment]
Hi @khalidEssouidi, currently I see this

<img width="226" alt="image" src="https://user-images.githubusercontent.com/5917993/217357822-9da9b6bc-3d13-4137-a925-6dc0f7b4e177.png">

The folder is also with name in Pascal case => Configs.

Indeed, linus is case sentitive but when you deploy a pod the config files must not be part of the image. The configuration files must be defined via a configmap. 
Check the open source project https://github.com/GFlisch/Arc4u.Guidance.Workflows you will see the Build and Publish workflow (where the Configs folder is removed) and the AKS one which create a configmap with the file correctly named.
The Configs folder is the name of the configmap, not the generated one by the guidance.

Gilles

Tell me if this is ok for you by closing the issue or continue the discussion.
