### ISSUE TITLE
Guidance does not add code for configuring service to the program.cs

### ISSUE THREAD

**Issue by fdeceuny** [GFlisch/Arc4u.Guidance.Doc#121]
The latest version of the Guidance no long adds code for configuring the service when adding a service account to the Service Agent.
This seemed to be an issue getting the SA to an existing service to work in Ademar AvailabilityMonitoring.
According to Fabian Dutrieux/Mark Malek this would have worked in previous versions of the Guidance.

```
    services.AddHttpClient("Service", (httpClient) =>
    {
        httpClient.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
        httpClient.DefaultRequestVersion = HttpVersion.Version20;
    })
    .AddHttpMessageHandler<ServiceHttpHandler>();     

    services.AddHttpClient("MailSender", (httpClient) =>
    {
        httpClient.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
        httpClient.DefaultRequestVersion = HttpVersion.Version20;
    })
    .AddHttpMessageHandler<MailSenderHttpHandler>();
```

**Comment by GFlisch** [comment]
Hi @fdeceuny,

I have tried and done an example.

I have a Core1 and Core2 services. Core1 is implementing a facade and in the Core2 a Core1SA has been created.
When I have added a proxy to Core1. The program.cs is well updated.

	services.AddHttpClient("Core1", (httpClient) =>
				{
					httpClient.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
					httpClient.DefaultRequestVersion = HttpVersion.Version20;
				})
	.AddHttpMessageHandler<OAuth2HttpHandler>()
	.AddTransientHttpErrorPolicy(p => p.WaitAndRetryAsync(3, _ => TimeSpan.FromMilliseconds(200)));

So everything seems to work correctly for me. 

Can you set in the Guidance2022 option menu set the logging to verbose and see in the Output window is an error is logged. This can help me to diagnose the isse?

**Comment by fdeceuny** [comment]
Tested it and it works. Was a misinterpretation of the functionality.
