### ISSUE TITLE
(Guidance 2022.2.1.11) Unexplained change in controller routes

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#124]
When you add a new back-end, the route of the EnvironmentController has changed.
It is now:

~~~csharp
/// <summary>
/// Services about the application information.
/// </summary>
[Authorize]
[ApiController]
[Route("/Service/facade/[controller]")]
[ApiExplorerSettings(GroupName = "facade")]
[ProducesResponseType(typeof(IEnumerable<Message>), StatusCodes.Status400BadRequest)]
public class EnvironmentController : ControllerBase
~~~

It used to be:

~~~csharp
/// <summary>
/// Services about the application information.
/// </summary>
[Authorize]
[ApiController]
[Route("facade/[controller]")]
[ApiExplorerSettings(GroupName = "facade")]
[ProducesResponseType(typeof(IEnumerable<Message>), StatusCodes.Status400BadRequest)]
public class EnvironmentController : ControllerBase
~~~

The change is hidden because the corresponding route in Yarp's `reverseproxy.json` was changed accordingly:

~~~json
      "service/environment": {
        "ClusterId": "service",
        "AuthorizationPolicy": "Default",
        "Match": {
          "Path": "/service/facade/environment/{**remainder}"
        },
        "Transforms": [
          {
            "PathPattern": "/service/facade/environment/{**remainder}"
          }
        ]
      }
~~~

However, there should be an explanation why the prefix of the route to a controller of a service should now contain the name of that service, and why this adds value.

It's also confusing for new services being added to existing projects generated by a previous version of the guidance.

It also contradicts the swagger endpoint path

**Comment by rdarko** [comment]
On the client side, the error looks like this https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/152
This is the backend problem. Nothing should be done in the frontend.

**Comment by vvdb-architecture** [comment]
This change is a side effect of changes made to simplify `reverseproxy.json`, as mentioned in https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/125
