### ISSUE TITLE
(Bug, Nova 2.0.1): Nova stylesheets contains hard-coded links to assets in http://localhost:9000

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#128]
When starting a Guidance-generated Blazor application with Nova 2.0.1, the following is observed:
![novashit](https://user-images.githubusercontent.com/66954369/217825035-f794d717-47c7-411f-944d-5f3d7c03a41b.PNG)

The `CONNECTION REFUSED` error are due to hard-coded Urls inside Nova's stylesheets, which always point to http: //localhost:9000 regardless what the endpoint of your Blazor is.

The error is not noticed outside the console since it fails on loading font files, which is not a breaking error, but will probably break Nova functions that rely on these fonts to be loaded correctly.
For example, the strange white square in front of 'Home':

![image](https://user-images.githubusercontent.com/66954369/217826682-cdb3a361-0835-4892-b5cb-cea1fc7f00d5.png)

**Comment by maxime-poulain** [comment]
Hello,
I haven't use Nova (yet) so the following might be not applicable:

Fonts and the css should be embedded inside the NuGet.
If Nova is a Razor Class Libarry, then the following is the good approach to go:
https://learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-7.0&tabs=visual-studio#consume-content-from-a-referenced-rcl

Your Blazor WASM's index.HTML would look like this:
![image](https://user-images.githubusercontent.com/6811304/220212461-e66e80e2-52b8-4279-900e-88594850a9c0.png)

**Comment by rdarko** [comment]
With introduction of the nova 2.5 this will be solved. This will introduce a namespace change

**Comment by vvdb-architecture** [comment]
no more hard-coded links in Nova 2.2.5, but problems still remain. No styling
![image](https://user-images.githubusercontent.com/66954369/228531671-93fca2e4-ae2e-4404-9a97-5d9df49ee18b.png)
