### ISSUE TITLE
(improvement, Guidance 2022.2.1.11): eliminate CS in DatabaseContextForMigrationFactory 

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#129]
When generating the migration tool, the DatabaseContextForMigrationFactory is generated as follows:

~~~csharp
public class DatabaseContextForMigrationFactory : IDesignTimeDbContextFactory<DatabaseContext>
{
    public DatabaseContext CreateDbContext(string[] args)
    {
        return Program.Container().GetService<DatabaseContext>();
    }
}
~~~

This triggers:
> DatabaseContextForMigration.cs(10,16,10,65): warning CS8603: Possible null reference return.

It is an error to return a null reference from the method, the code should therefore be changed to:

~~~csharp
public class DatabaseContextForMigrationFactory : IDesignTimeDbContextFactory<DatabaseContext>
{
    public DatabaseContext CreateDbContext(string[] args)
    {
        return Program.Container().GetRequiredService<DatabaseContext>();
    }
~~~

No warning will be generated.

**Comment by GFlisch** [comment]
Done.

Will be in the version 2012.2.1.12.

Thanks.
