### ISSUE TITLE
Add support for optional local appsettings

### ISSUE THREAD

**Issue by maxime-poulain** [GFlisch/Arc4u.Guidance.Doc#134]
#  **Is your feature request related to a problem? Please describe.**

Currently Guidance does not provide a way out of the box to have a `personal appsetting.json`.
A common usage is to use something like
`Configa/ppsessting.Local.json`.

#  **Describe the solution you'd like**
# A clear and concise description of what you want to happen.

The idea is to have the following code:

```csharp
    builder.Host
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            IConfigurationSource? secrets = null;
            foreach (var source in config.Sources.Where(s => s.GetType().Name.Contains("Json")).ToList())
            {
                config.Sources.Remove(source);
            }

            var env = hostingContext.HostingEnvironment.EnvironmentName;

            config.AddJsonFile("configs/appsettings.json", true, true);
            config.AddJsonFile($"configs/appsettings.{env}.json", true, true);
            config.AddJsonFile($"configs/appsettings.Local.json", true, true);  // <-- optional json
        })
```

There are situation while developing where one wants to override specific settings.
`appsetting.Development.json`

```json
  "Dipole": {
    "ExcelFilePath": null,
    "MappingResultSheetName": null,
    "EmailRecipient": null
  }
```

I don't want the `EmailRecipient` be defined in the above configuration file;
I want mails to be sent to me but I don't want to have hardcoded my own email
This is for the sake of any developer that could at some point be working on the project.

There is just one thing that needs to be done to have this working without an issue
The `appseting.Local.json` must be defined in the `gitignore` file.
this would not make sense otherwise.

an example would  be in my case:

# **Describe alternatives you've considered**

Visual Studio / dotnet already providfes a way to achieve that thanks to the
`secrets.json` configuration file.

![image](https://user-images.githubusercontent.com/6811304/220271364-1778266c-7119-418b-b0b3-8eee65d3cd81.png)

This opens:

![image](https://user-images.githubusercontent.com/6811304/220271683-db3c4e5e-c107-478a-86bf-65d3784a6315.png)

Using this is however not possible currently because the following code 

```csharp
            foreach (var source in config.Sources.Where(s => s.GetType().Name.Contains("Json")).ToList())
            {
                config.Sources.Remove(source);
            }
````

An alternative to fix that would be

```csharp
    builder.Host
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            var env = hostingContext.HostingEnvironment.EnvironmentName;

            IConfigurationSource? secrets = null;
            foreach (var source in config.Sources.Where(s =>
                         s.GetType().Name.Contains("Json")).ToList())
            {
                config.Sources.Remove(source);
                if (env == Environments.Development  && source is FileConfigurationSource { Path: "secrets.json" })
                {
                    secrets = source;
                }
            }


            config.AddJsonFile("configs/appsettings.json", true, true);
            config.AddJsonFile($"configs/appsettings.{env}.json", true, true);
            if (secrets is not null)
            {
                config.Sources.Add(secrets!); // <-- secrets.json have precedence over everywhere
            }
        })
```

Restoring `secrets.json` is done only on the `Development` environment.

**Comment by GFlisch** [comment]
@maxime-poulain, the local environment for a developer is something easy to do and I will not implementing it in the Guidance.

Now, we have a feature where data is encrypted in the configuration file which is far better for me than the manage user secrets of Microsoft. The main reason is that the secrets are saved on the Git repo.

I will set this as done => via the encryption mechanism.

**Comment by maxime-poulain** [comment]
> We have a feature where data is encrypted in the configuration file

Oh I did not know, I will investigate more information on that :).
