### ISSUE TITLE
Visual studio is getting stuck when using Guidance

### ISSUE THREAD

**Issue by rdarko** [GFlisch/Arc4u.Guidance.Doc#136]
**Information**
Visual studio is getting stuck when i try to use the Guidance

**Describe the bug**
When i right click the visual studio, the Guidance opitons are not shown, sometimes it getting stuck.

**To Reproduce**
Its sometimes get stuck so its difficult to reproduce.

**Expected behavior**
Not stuck

**Desktop (please complete the following information):**
 - Visual Studio Version 17.4.4. but it was also working similiar with previous versions
 - Guidance 2022.2.1.11 installed

written together with ykhales

**Comment by rdarko** [comment]
ykhales are you using remote desktop?

**Comment by norexia** [comment]
Yes,  I use my internal remote desktop .
