### ISSUE TITLE
(bug, Guidance2022.2.1.12-rc1): Including Nova messes up the project - again.

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#144]
When you generate a Blazor client, the inclusion of

~~~xml
    <PackageReference Include="Nova" Version="2.0.1" />
~~~

... messes up the project by adding an "assets" shortcut in the project pointing to files in the NuGet local directory:

![image](https://user-images.githubusercontent.com/66954369/224676337-13d12924-49ed-4ad8-87ec-1c1d5cb10304.png)

Removing the Nova 2.0.1 reference removes this "assets" shortcut. There is no point for this or any other package to do this, so this needs to be fixed.

Upgrading Nova to the latest 2.2.5 version does not correct the problem, but only package.json and the figma directory remain. The scripts directory has gone. This is still not acceptable.

Files in NuGet local directories should never be part of a project. Github reacts accordingly when you want to create a repository out of it:
![image](https://user-images.githubusercontent.com/66954369/224699772-d9608c69-0bd2-45e8-b8c3-17b44804be17.png)

This is a repeat from https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/127

**Comment by GFlisch** [comment]
Yes, this is a nova package issue => I have to integrate the latest version nova blazor 2.5 which fix this. This will be for Friday.

**Comment by vvdb-architecture** [comment]
Still present in -rc3 with Nova 2.2.5
