### ISSUE TITLE
(bug, Guidance2022.2.1.12-rc1): Adding an EF Core database project contains a mix of 6.0.11 and 6.0.12 references

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#148]
When you add an EF Core database project, you get Arc4u references to 6.0.12.x but Microsoft packages for 6.0.11.

~~~xml
  <ItemGroup>
    <PackageReference Include="Arc4u.Standard.EFCore" Version="6.0.12.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.11" />
  </ItemGroup>
~~~

This is the same behavior noticed in https://github.com/GFlisch/Arc4u.Guidance.Doc/issues/145. Even if it does not generate downgrade errors, versions should be harmonized throughout the solution.

**Comment by GFlisch** [comment]
Fix and publish => Ef Core Database Project, Migration and Core service host,

**Comment by vvdb-architecture** [comment]
Fixed in rc3
