### ISSUE TITLE
Use decorator pattern in combination with DI

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#15]
Sometimes it is (imho) a good practice to use the decorator pattern within the DI.
For example, there is a service gathering all registered users.
```csharp
public interface IUserService
{
   IEnumerable<string> GetRegisteredUsers();
}
```
with an implementation like this
```csharp
internal class UserService : IUserService 
{
   public UserService(DatabaseContext context) => _context = context;
   public ICollection<string> GetRegisteredUsers() => _context.Users.ToList();
}
```

This operation seems to be expensive, because it will gather *all* rows from a database table. So we might want to cache that.
Adding the caching to `UserService` is actually violating the Single Responsibility pattern, because the class would then do caching AND data gathering. Therefore I am in favour of having a decorator taking care of those things.
```csharp
internal class CachingUserServiceDecorator : IUserService 
{
   public CachingUserServiceDecorator(CachePolicy cachePolicy, IUserService decoree) 
   {
      _decoree = decoree;
      _cachePolicy = cachePolicy;
   }

   public ICollection<string> GetRegisteredUsers() => _cachePolicy.Execute(
              _ => _decoree.GetRegisteredUsers(),
              new Context($"{this.GetType().Name}.{nameof(GetRegisteredUsers)}"
   );
}
```

We can now register the service and its decorator like this for example
```csharp
services.AddScoped<IUserService, UserService>();
services.Decorate<IUserService, CachingUserServiceDecorator>();
```
(There are multiple implemenations / IoC Container providing a decorator pattern)

You could imagine multiple layers of decorators this way. For example imagine the following
```csharp
services.AddScoped<IUserService, UserService>();
services.Decorate<IUserService, LoggingUserServiceDecorator>();  // Logging how many users where found, how long the request was running etc
services.Decorate<IUserService, RetryUserServiceDecorator>(); // retrying, if the database was not available or ran into an timeout etc
services.Decorate<IUserService, CachingUserServiceDecorator>(); // caching the requested data
```

Those registrations can also be independent. So maybe in one module the actual service was registered, but the decorators in another. This way the decorator does not need to know anything about the actual service implementation and can be totally independent. Both the service and the decorators can be easily tested etc.

**Comment by vvdb-architecture** [comment]
We will stick with MS DI for the time being, decorator patterns are not used often enough to warrant this change.
