### ISSUE TITLE
(bug, Guidance2022.2.1.12-rc1): Adding a Hangfire job has missing operation

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#150]
When you add a hangfire project and a hangfire job, the following error occurs:

~~~
C:\PRJ\HappyFlow\TestFlow\BE\Service\TestFlow.Service.Host\Infrastructure\HangfireAuthorization.cs(14,104,14,114): error CS0117: 'Access' does not contain a definition for 'CanSeeJobs'
~~~

The `CanSeeJobs` should be an operation of the shared `Access` type.

**Comment by GFlisch** [comment]
Will be solved by implementing a generator access api. Need time to implement this.

**Comment by rdarko** [comment]
fixed
