### ISSUE TITLE
not possible to generate configuration files for additional environments

### ISSUE THREAD

**Issue by refactorinc** [GFlisch/Arc4u.Guidance.Doc#163]
**Is your feature request related to a problem? Please describe.**
It appears that it's currently not possible to generate configuration files for additional environments.
E.g. a 2nd test environment, a 2nd acceptance environment, a demo environment, ...

**Describe the solution you'd like**
An option to generate configuration files for additional environments.
Inputs:
- new environment name
- adfs environment
- Or 'create additional dev/test/acc/prod environment' because - for the moment - there are only these 4 adfs environments at Elia

**Describe alternatives you've considered**
Doing everything manually but it takes time and other tasks don't get done

**Comment by rdarko** [comment]
Hi, this will bring too much complexity for the guidance and only little gain for the architects and devs. We find that it is much easier to copy paste and customise the appsettings for all additional environemnts.
