### ISSUE TITLE
Generated BuildAndPublish.yml does not include a trigger for master

### ISSUE THREAD

**Issue by refactorinc** [GFlisch/Arc4u.Guidance.Doc#166]
**Describe the bug**
`master` branch is not included in the triggers defined in BuildAndPublish.yml

**To Reproduce**
1. Create blank solution
2. Do a guidance solution generation

**Expected behavior**
`master` branch is included in the triggers defined in BuildAndPublish.yml

**Desktop (please complete the following information):**
 - Visual Studio Version 17.4.1
 - Guidance Version 2022.2.1.11

**Additional context**
The Azure DevOps version in use on-premise initializes git repositories with a branch named `master`

**Comment by rdarko** [comment]
This can be fixed in the templates only, without having a new release.

**Comment by HaGGi13** [comment]
As discussed, this can be a solution, if the `main` branch should be supported too. If not, it can be removed.  
The `paths` section remains untouched.

```yaml
trigger:
  branches:
    include:     
    - main
    - master
    - release/*
    - develop/*
```

**Comment by HaGGi13** [comment]
The change was done in the hook-in template and will be available by a new Guidance version.
