### ISSUE TITLE
Missing license key error message is very confusing

### ISSUE THREAD

**Issue by phoogers** [GFlisch/Arc4u.Guidance.Doc#170]
**Describe the bug**
When starting from scratch and trying to create a guidance scaffolded solution without a license key, the guidance will just not do anything but not tell you **why** it doesn't want to do what you ask it to.

**To Reproduce**
When starting with a new VS2022 after having installed the guidance package, I wanted to create a guidance solution.
I:
- created a blank solution
- right clicked the solution and clicked "Create Arc4u AspNetCore Solution => 2022.2.1"
Nothing happens, no error message either.
If you go look at the output of the Arc4u.Guidance 2022.2.1 you see following error message:

![image](https://user-images.githubusercontent.com/20597158/235110090-41d0b34d-b86e-4b24-9ede-bc099aa495a0.png)

This looks like a technical error message but after asking around, this is the error message when your license key is not entered.

**Expected behavior**
- after clicking "Create Arc4u AspNetCore Solution => 2022.2.1" the user should get an informative message such as "Your license key is not filled in and/or expired. Please check your configuration in Tools --> Options --> Guidance 2022"
- In the output window, the error message can be more clear, like "No license key found"

**Comment by rdarko** [comment]
Hi @phoogers , can you please validate that this is fixed in 2022.2.1.16?
Thanks!
