### ISSUE TITLE
standard generated BuildAndPublish.yml files

### ISSUE THREAD

**Issue by phoogers** [GFlisch/Arc4u.Guidance.Doc#182]
There is a pipeline parameter "buildconfiguration" foreseen (by default set to Release) but this is never actually hooked up to the template parameters.

basically just 1 line that needs to be added:

![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/20597158/a2a1dac4-a400-4781-91c1-375628ad3677)

See also commit dfc5e069b23d42443b70756bc838d5b2600592a9 in the group collection - project Infraref

**Comment by GFlisch** [comment]
Hi @phoogers , after thinking about this we will adopt the strategy to remove the variable and using the default.

So if in your case you need to change it, you will have to add buildConfiguration: '????' directly to the file and not in the variable like before.

**Comment by HaGGi13** [comment]
This change was already done in the hook-in template and is merged.
