### ISSUE TITLE
Add a WPF project: "nativeAppDisplayName" is identical for "DEV" and "DEVELOPMENT"

### ISSUE THREAD

**Issue by bibheist-unity** [GFlisch/Arc4u.Guidance.Doc#183]
**Describe the bug**
When the guidance is used to add a new WPF project, the JSON configuration files generated in the folder "OAuth2" include the same value for the property "_nativeAppDisplayName_" for the environment "_DEV_" and "_DEVELOPMENT_".  

Therefore, if the JSON files for DEV and DEVELOPMENT are submitted for ADFS registration, the last submitted one will be refused because ADFS raises an exception due to the duplication of the application name.

**To Reproduce**
1. Open a solution initiated by Guidance
2. Add a new WPF project
3. Open the JSON configuration files present in the folder "OAuth2" for DEV and DEVELOPMENT

**Expected behavior**
Ideally, the value for the property "_nativeAppDisplayName_" should contains the name of the application including a suffix (ex: "LocalHost") for the environment "_DEVELOPMENT_".  This avoids any ambiguity.

**Desktop (please complete the following information):**
 - Visual Studio 2022 Version 17.4.1
 - Guidance Version 2022.2.1

**Comment by vvdb-architecture** [comment]
The native application display name is local to the application group. As long as the application group name is different, the native application name can be anything as long as it is unique within the ADFS group.

Please show exactly what will be refused and how you know that it will be refused.

**Comment by bibheist-unity** [comment]
Of course!

The automated e-mail sent back by ADFS includes this error message:

`Executing RegisterNativeApplication
RedirectUri =   urn://outageplanningtool.basic.authentication Native application clientId :  3a18cf4f-1a68-4016-8931-028257c0c140
Executing RegisterNativeApplication
RedirectUri =   http://localhost/ MSIS7605: **The name of the client must be unique across all clients**.     + CategoryInfo          : InvalidData: (Microsoft.Ident...ientApplication: 
   NativeClientApplication) [Add-AdfsNativeClientApplication], StorageConstra
  intException
    + FullyQualifiedErrorId : MSIS7605,Microsoft.IdentityServer.Management.Com 
    mands.AddAdfsNativeClientApplicationCommand
     + PSComputerName        : SBISTSS1001.belgrid.net
 Native application clientId :`

**Comment by GFlisch** [comment]
I propose to discuss about this in the monthly meeting.

Do we add or not the environment name in the nativeAppDisplayName?

@bibheist-unity, is it ok for you to proceed like this?

**Comment by bibheist-unity** [comment]
Yes ! Of course.Le 18 juil. 2023 à 08:01, GFlisch ***@***.***> a écrit :﻿
I propose to discuss about this in the monthly meeting.
Do we add or not the environment name in the nativeAppDisplayName?
@bibheist-unity, is it ok for you to proceed like this?

**Comment by rdarko** [comment]
To be checked if it can be solved by changing the template only. If not, it should be moved to the bugfixing sprint

**Comment by GFlisch** [comment]
Will be fixed in the version 14.
