### ISSUE TITLE
Verify/create the 'Rules' and 'Validators' folders when creating a new BL class

### ISSUE THREAD

**Issue by SSantiagoDev** [GFlisch/Arc4u.Guidance.Doc#185]
**Description of the bug**
An architect created a new solution on his machine, committed it to Git, then I took it on my machine.
Git doesn't save an empty folder. So when pushing the new solution to Git, the 'Rules' and 'Validators' folders from the Business project, they only "exist" in the csproj, but not physically. When we ask to create a new BL class, a check should be made to be sure that these folders exist (and if not, create them). The BL class is not created and there is no error message.

**To Reproduce**
1. Create a new solution with the Guidance
2. Commit to Git
3. Create a new domain entity
4. Create a new BL class

**Expected behavior**
The BL class should be created. Not the case currently with this configuration.

**Screenshots**
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/2098804/2cc6b749-a0bd-4cfb-86c7-b78e10f7576d)
The folders need to be created manually to be able to create the BL class:
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/2098804/18e0e90e-2153-4f16-a0cf-70d8f5a46231)

**Desktop:**
 - Visual Studio Version 17.2.5
 - Guidance Version 2022.2.1.12

**Comment by GFlisch** [comment]
Hi @SSantiagoDev, 
I have done a test (by deleting the Rules and Validators) folders based on the next code that will be released. But this one has not changed for me.
As the Guidance is not generating any Rules, indeed the Rules folder is not created but the Validators one well.



![Image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/5917993/968e9882-ad5d-4ae6-83a6-aee4167a90e1)

As you can see here, the Settlement validators where well added below the created folder Logic\Validators.

I will not close this and propose that you keep an eye on this when the new version is released.
