### ISSUE TITLE
New Interface assembly missing in Application.Dependency (config file) when creating a new Interface project with the Guidance

### ISSUE THREAD

**Issue by SSantiagoDev** [GFlisch/Arc4u.Guidance.Doc#189]
**Description of the bug**
Starting from a new solution, when creating a new interface with the Guidance, the config section Application.Dependency is missing: "Assembly": "PROJECTNAME.Core.Interface"

**To Reproduce**
1. Create a new Solution with the Guidance
2. Create a new Interface

**Expected behavior**
The config file should be adapted by the Guidance so we don't have to manually add "Assembly": "PROJECTNAME.Core.Interface" in the section Application.Dependency.

**Desktop (please complete the following information):**
 - Visual Studio Version 17.2.5
 - Guidance Version 2022.2.1.12

**Comment by GFlisch** [comment]
Thanks for the issue found.
This is fixed and will be part of the new version coming soon.
