### ISSUE TITLE
Add business class from existing entity does nothing.

### ISSUE THREAD

**Issue by Guy-Heylens-Elia** [GFlisch/Arc4u.Guidance.Doc#190]
**Information**
If the bug is linked to the Arc4u framework, please go to the [Arc4u repo](https://github.com/GFlisch/Arc4u/issues).

**Describe the bug**
Right click to generate a business class does nothing.

**To Reproduce**
1. Create an entity in the Domain layer.
2. Build project.
3. Right click Business layer and select "Add business class from existing entity"
4. The context menu closes and nothing happens.

**Expected behavior**
A business class is created.

**Screenshots**
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/104833610/00b19404-31b7-4698-871a-4a5b95fd2f8a)

**Desktop (please complete the following information):**
 - Visual Studio Version 17.2.5
 - Guidance Version 2022.2.1.12

**Additional context**
Same problem exists when you do this on Database layer.

**Comment by HaGGi13** [comment]
This should be fixed in Guidance 2022.1.13, but we'll tets it again to double-check.
