### ISSUE TITLE
YARP Denial of Service Vulnerability

### ISSUE THREAD

**Issue by David-vh** [GFlisch/Arc4u.Guidance.Doc#191]
When generating a new project the yarp version that is used (1.1.1) contains a Denial of Service Vulnerability
see: https://github.com/microsoft/reverse-proxy/security/advisories/GHSA-8xc6-g8xw-h2c4

Upgrade yarp version to 1.1.2 to solve vulnerability

**Comment by HaGGi13** [comment]
The new version will shop version 2.0.1.
