### ISSUE TITLE
Fatal error on opening a project

### ISSUE THREAD

**Issue by WaldemarKaib** [GFlisch/Arc4u.Guidance.Doc#194]
**Describe the bug**
After installing the newest version (2022.2.1.13) there is an error in the Output window, when opening any project:
`Error: 21.08.2023 11:17:56 Utc : OnAfterOpenSolutionAsync => An error occurred while sending the request.`
As a result, guidance functions can no longer be executed

**To Reproduce**
1. Install version 2022.2.1.13
2. Open any project

**Expected behavior**
There should be no error and the guidance functions (like crating a Blazor frontend) should work.

**Screenshots**
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/125976352/1a7f1d97-dba5-4207-8332-cdd580bb602d)

**Desktop (please complete the following information):**
 - VisualStudio.17.Release/17.5.4+33530.505
 - Guidance Version 2022.2.1.13

**Comment by rdarko** [comment]
If this was related to the certificate, the certificate issue is solved. If this is not the case, please ping us.
