### ISSUE TITLE
Adding a new Blazor project does not build

### ISSUE THREAD

**Issue by poldepuysseleyr** [GFlisch/Arc4u.Guidance.Doc#198]
**Describe the bug**
Adding a new Blazor web project does not build from the get go.

**First bug:**
Visual studio detects 3 nuget packages that are a downgrade:

- Blazored.LocalStorage
- Microsoft.AspNetCore.Components.WebAssembly
- Microsoft.AspNetCore.Components.Authorization

**Second bug:**
OAuth2HttpHandler.cs and OAuth2TokenSettingsReader.cs seem to be missing in the Infrastructure folder,
but are defined in an ItemGroup as included on compile time in the csproj.

These are also required in the Program.cs line 32.

**Third bug:**
In Program.cs line 58 in the services.AddScopedOperationsPolicy method, Operations get passed but these are not defined in the project.
This is probably something we have to add manually, but a disclaimer could come in handy.

**To Reproduce**
1. In a new project after defining the backend, add a new blazor project through the Guidance in the FE folder.
2. Build the solution
4. See errors

**Expected behavior**
First bug:
Upgrading the packages to the correct version. Tested this myself.
I manually updated the version in the csproj as in screenshot to the required version and the error was gone.
![Nuget upgrade](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/10937600/2a00edf0-1d82-4b86-aef9-7bf8605d6596)

Second bug:
Make sure files are present in the Infrastructure folder. 
I copy pasted them from another project (SN 4.0), then removed the ItemGroup in the csproj, added import in Program.cs and errors were resolved.

Third bug:
No error anymore for operations. Maybe a disclaimer what we should pass through here.
I did this just so I could move on in the project.
![operations fix](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/10937600/ad64346a-29cf-4893-a995-decbe540e8b9)

**Screenshots**
**First bug:**
![Error when adding new blazor project](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/10937600/0e55d550-af01-48d8-873e-644d0af5de82)

**Second bug**:
![OAuth2 errors](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/10937600/eac69879-139b-4b29-a450-c62dda4532b2)

**Third bug**:
![Program cs errors](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/10937600/db61990b-6413-4f84-8a6a-7763bb9f966d)

**Desktop (please complete the following information):**
 - Visual Studio Version 17.5.33530.505
 - Guidance Version  2022.2.1.12)

**Comment by GFlisch** [comment]
Hi @poldepuysseleyr , this is due to the fact that the templates have been adapted to the Guidance 2022.2.1.13. You have first to update your project to 2022.2.1.13 before you can do this. Old Guidance script is applied to new templates and even classes that don’t exist anymore…

**Comment by poldepuysseleyr** [comment]
Ok, my bad. Did not see there was a new version yet. Sorry for the fake news then.

**Comment by GFlisch** [comment]
No issue @poldepuysseleyr .
