### ISSUE TITLE
Blazor authentication failure in DEV/TEST/... if the url contains no trailing slash

### ISSUE THREAD

**Issue by bitsdontbite** [GFlisch/Arc4u.Guidance.Doc#210]
**Describe the bug**
When deployed in DEV with IIS (with virtual path), the authentication mechanism in blazor fails without adding a trailing slash to the url.
For instance:
https://<myapp>dev.tmd.belgrid.net/ui causes an authentication failure
but:
https://<myapp>dev.tmd.belgrid.net/ui/ succeeds.

Most users will never add this trailing slash. It can be managed seamlessly by updating the code in RedirectToLogin.razor:
Just replace:
`Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");`

with something like:

var uri = Navigation.Uri;

if (!uri.EndsWith("/"))
    uri += "/";

Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(uri)}");

**Expected behavior**
Whether the user adds the trailing slash or not should work.

**Desktop:**
 - Visual Studio Version [17.5.4]
 - Guidance Version [e.g. 2022.2.1.12]

**Comment by rdarko** [comment]
According to V, the solution would be

**Comment by bitsdontbite** [comment]
That's it!

**Comment by vvdb-architecture** [comment]
Confirmed fixed in ACC
