### ISSUE TITLE
Nuget source url is specific to a company

### ISSUE THREAD

**Issue by rdarko** [GFlisch/Arc4u.Guidance.Doc#212]
**Describe the bug**
When i create a new solution, default source for nuget packages is a specific company nuget, and not https://api.nuget.org/v3/index.json

**To Reproduce**
1. Create a new solution
2. Try to rebuild
3. It gives an error
4. Go to Visual Studio - Tools - Nuget Pacakge Manager - Package Source - and check the url address - its a company specific
5. change it to above mentioned one
6. rebuild
7. check the source again

**Expected behavior**
i should either be asked which adress i want to use, or if i change it and rebuild, it should stay what i insert.

**Comment by GFlisch** [comment]
This is an expected behavior.
For your company this is not the public one.
I cannot go against your rules.
