### ISSUE TITLE
WPF desktop client generation: compensate for breaking change in MSAL default URI

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#215]
If you generate a WPF application with the latest version of the Guidance, you may find that authentication doesn't work as expected. 
More specifically, the requests sent will include a redirect URI of https://login.microsoftonline.com/common/oauth2/nativeclient instead of the expected http://localhost/.
If (and only if) you encounter this, the workaround is to replace in LoginPageVM.cs the line:

~~~csharp
.WithDefaultRedirectUri()
~~~

with 

~~~csharp
.WithRedirectUri("http://localhost")
~~~

It can be hardcoded, because you don't have a choice in the matter: it's always http://localhost/. 
 
I'm not sure when the Default Redirect Uri was changed and why, but it seems that from a certain version of MSAL, there is a distinction between ".NET Core" desktop apps and ".NET Core Windows" desktop apps. The former still uses localhost redirect, the latter uses the login.microsoftonline.com redirect.
You can see this in the MSAL.NET source code:

	
[microsoft-authentication-library-for-dotnet/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs at main · AzureAD/microsoft-authentication-library-for-dotnet (github.com)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs) (GetDefaultRedirectUri) 

	
[microsoft-authentication-library-for-dotnet/src/client/Microsoft.Identity.Client/Platforms/net6win/Net6WinPlatformProxy.cs at main · AzureAD/microsoft-authentication-library-for-dotnet (github.com)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/Platforms/net6win/Net6WinPlatformProxy.cs) (GetDefaultRedirectUri)
	
There is a factory in [microsoft-authentication-library-for-dotnet/src/client/Microsoft.Identity.Client/PlatformsCommon/Factories/PlatformProxyFactory.cs at main · AzureAD/microsoft-authentication-library-for-dotnet (github.com)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/PlatformsCommon/Factories/PlatformProxyFactory.cs) and for the the version we link our WPF apps with (via Arc4u), NET_CORE is not defined but NET6_WIN is.

 
Go figure....

**Comment by GFlisch** [comment]
Will be fixed in the next Guidance => Code generation. Not only templating.
