### ISSUE TITLE
Generate SDK yaml pipelines at same time as sdk is created

### ISSUE THREAD

**Issue by ddewaleffe** [GFlisch/Arc4u.Guidance.Doc#217]
The SDK pipelines (for interfaces and facades) definitions  seems to me sufficiently standard that they could be automatically generated by the guidance in a similar manner as the build piplines are for the backends. That would save many hours stupidly spent at fixing copy paste errors...

**Comment by rdarko** [comment]
could you please give us more information and clarify what the problem is?
Usually when issue/bug is created, the template is offered that needs to be filled.
In order to see it go here https://github.com/GFlisch/Arc4u.Guidance.Doc/issues and add new issue. Then you will see the template.

**Comment by rdarko** [comment]
From @ddewaleffe 
guidance generates the devops pipeline to  build each of the backends. This is good and handy.
When the guidance a facade or interface project, it could as well generate a small build pipeline that for the facade sdk and specially for the interface sdk . It is not very complicated to do and would shave off a few minutes of dumb work for each use. 
Given the guidance has all the details, it could even go as far as making sure the pipeline is only run when changes are made to the sdk files.

publishing the sdk to proget should probably be to avoid automatic pollution of the proget server.

**Comment by GFlisch** [comment]
We are considering to stop generating the Sdk for interface => this will be voted in the next architecture meeting.
