### ISSUE TITLE
MigrationTool execution failures are not propagated to the DevOps Release pipeline

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#219]
The code generated in `Program.cs` for a database migration tool declares the `Main` method as follows:

~~~csharp
static void Main(string[] args)
~~~

and that method ends with:

~~~csharp
        app.Execute(args);
~~~

A command is implemented to return 0 on success and -1 on failure:

~~~csharp
        app.Command("...", config =>
        {
            config.Description = "...";
            config.OnExecute(() =>
            {
                try
                {
                    // whatever code here.
                    return 0;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    return -1;
                }
            });
        });

~~~

The DevOps release pipelines are coded in such a way that process return values different from 0 will cause the migration step to fail.

Unfortunately, this will never happen: because of the `void Main` declaration, the process always returns 0.

To fix this, you need to declare the `Main` method as follows:

~~~csharp
static int Main(string[] args)
~~~

and the last line should just return the value of the command that has been applied:

~~~csharp
return app.Execute(args);
~~~

Methinks this is a template issue.

**Comment by GFlisch** [comment]
Updated on the templating project. Will be part of the templating changes.
Thanks.

**Comment by vvdb-architecture** [comment]
Confirmed fixed in ACC
