### ISSUE TITLE
Bug in Guidance plugin: missing Blazor files

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#22]
Steps to reproduce:

- make sure you have the Acr4u Guidance 2022 [Preview] 2022.2.1.8 installed.
- Create a blank solution, and an Arc4u solution using the plugin.
- Create a service (any name will do)
- Create a Blazor client

The Blazor client doesn't start.
In wwwroot, there is an empty Blazor/Web folder containing no files.
There is no html start page for Blazor, no css stylesheets, etc...

**Comment by GFlisch** [comment]
Hi @vvdb-architecture,

The issue has been fixed and deployed. No need to change the Guidance for this. 

Program.cs has been adapted to fix the issue concerning the App namespace conflict.
builder.RootComponents.Add<$(company).$(solutionname).$(projectname).App>("#app");

Packages are now upgraded to 6.0.8.3.

Can you confirm this is ok and clause this issue if OK?
