### ISSUE TITLE
Register an application in ADFS: the generated ApplicationKey contains the word Decrypt instead of Encrypt

### ISSUE THREAD

**Issue by AdrianMMoga** [GFlisch/Arc4u.Guidance.Doc#228]
I have registered in ADFS an application using Arc4U 6.0.12.1 
The ApplicationKey generated automatically by the ADFS scripts contain "Decrypt" and instead, they should contain "Encrypt"

**To Reproduce**
1. Register an application in ADFS 
2. In the email received, ApplicationKey contains Decrypt instead of Encrypt
3. Update the config files in the application
4. Received authentication error

**Comment by GFlisch** [comment]
Hi @AdrianMMoga ,

This is not a topic related to the Guidance but more a specific implementation linked to a specific implementation in the company where you are working on.
