### ISSUE TITLE
[Spike] Define the way to integrate resilience and secrets in the Guidance

### ISSUE THREAD

**Issue by rdarko** [GFlisch/Arc4u.Guidance.Doc#252]
When you create a pub sub, secret should be added most of the time, discuss it with the developers, if we do it automatically or manually

**Comment by rdarko** [comment]
When you create a pub sub, secret should be added most of the time, discuss it with the developers, if we do it automatically or manually

**Comment by GFlisch** [comment]
For the moment, the first version will let the developer add this manually. We will see in the future if based on the user experience, requests will come to ease this integration.
