### ISSUE TITLE
AddMSalAuthentication AdditionalScopesToConsent not working, need to use DefaultAccessTokenScopes

### ISSUE THREAD

**Issue by gogessj4** [GFlisch/Arc4u.Guidance.Doc#258]
**Information**
AddMSalAuthentication AdditionalScopesToConsent not working, need to use DefaultAccessTokenScopes

**Describe the bug**
Pre .Net 8  AdditionalScopesToConsent  was used to add scopes to the addmsalauthentication configuration.
However this seems to be broken in .net 8, so DefaultAccessTokenScopes needs to be used instead.

**Desktop (please complete the following information):**
 - Visual Studio Version 17.9.7
 - Guidance Version 2022.2.1

**Comment by rdarko** [comment]
MSal will be removed to use identityModel.oidcclient instead. If its not fixed, please reopen
