### ISSUE TITLE
External Configuration

### ISSUE THREAD

**Issue by devbrsa** [GFlisch/Arc4u.Guidance.Doc#27]
It could lead sometimes to have more than 50+ configuration files for big projects, leading to error-prone and deployment issues.
Instead of leveraging on config files we could use an external configuration store, also provisioned in microservices.

https://learn.microsoft.com/en-us/azure/architecture/patterns/external-configuration-store
https://dzone.com/articles/microservices-externalized-configuration#:~:text=Externalized%20configuration%20works%20by%20keeping,configuration%20from%20the%20external%20store.

**Comment by vvdb-architecture** [comment]
Agree. I would even go one step further and use a store secure enough for storing secrets.

That's a known problem today (and one which existed before today). The only thing the Arc4u framework can do is to make sure it is ready to handle future configuration stores.  For Arc4u, there is some rethinking to do regarding stuff like `IKeyValueSettings`, but that's a topic for another discussion.

But... the main problem here is introducing, setting up and maintaining a configuration store, and that's a job for Infrastructure, not the Arc4u framework.

**Comment by rdarko** [comment]
there is an improvement which will be released (in beta). EFCore Configuration is able to achieve that
