### ISSUE TITLE
Implement Locking for distributed algorithms

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#32]

**Comment by devbrsa** [comment]
+1

**Comment by rdarko** [comment]
The locking of distributed algorithems is currently supported by Hangfire.
https://docs.hangfire.io/en/latest/background-processing/throttling.html
https://docs.hangfire.io/en/latest/background-processing/running-multiple-server-instances.html
When the problem reoccures, this issue will be reopened. Jan, if you disagree, please leave a comment.
