### ISSUE TITLE
Security header for .net appilcations

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#33]

**Comment by GFlisch** [comment]
Khalid has implemented something for Blazor.
CORS definition.
=> BE no need.
=> Yarp => via config

Http header => like in Epic
CSP => for front end and backend.
https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders

Add this on All the services even Blazor

**Comment by GFlisch** [comment]
Check if there is a way in .net core to build a policy from the appSettings file without to have to "build" this by our own.

**Comment by rdarko** [comment]
Still needs to be tested

**Comment by GFlisch** [comment]
Already released
