### ISSUE TITLE
Efficient Json/Compressed Json as alternative for Protobuf-based serialization

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#51]
Protobuf, and more specifically Protobuf.Net is not ideal for on-the-fly serialization. It is really defined for messages whose prototypes are fixed and known beforehand.

We could also use attributes. But we want to avoid contaminating our data type with Protobuf-specific attributes, which is not always possible and creates a dependency on a specific library external library.  Therefore, we need to keep track of the encountered types and build their runtime type model dynamically. 

This is essentially what [RuntimeTypeModelUpdater.cs](https://github.com/GFlisch/Arc4u/blob/master/src/Arc4u.Standard.Serializer.Protobuf/RuntimeTypeModelUpdater.cs) does in Arc4u and as you can see it's very messy. This complexity is a [code smell](https://en.wikipedia.org/wiki/Code_smell).

We are also dependent on the maintainers of Protobuf.NET. See #44.  Internally, ASP.NET Core uses `Google.Protobuf` instead, which do not fit our purpose since it is purely prototype based.

The pull request below defines a new `JsonSerialization2` which is Json serialization similar to `JsonSerialization` but with 3 changes:
- it allows serialization options to be passed during construction, which allows the inclusion of custom converters or any other setting.
- it allows for a serialization context, thereby supporting .NET 6+ [Source Generation](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-6-0).  For an explanation of why this is important, see [this](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#:~:text=%2Dup%E2%80%9D%20phase.-,The%20System.,instances%20of%20structured%20serialization%20metadata.).
- it offers the option to compress the result
- it's faster than the existing `JsonSerialization` implementation and generates less heap pressure.

There is a unit test called `CheckRuntimeTypeModelConcurrencyAsync` that illustrates the performance of the 4 methods that are now present:
- Protobuf for the existing `ProtoBufSerialization` serialization
- ProtobufZip for the existing `ProtoBufZipSerialization` serialization
- JsonSerialization for the existing `JsonSerialization` serialization
- JsonSerialization2(compressed : false) for the new `JsonSerialization2` without compression
- JsonSerialization2(compressed : true) for the new `JsonSerialization2` with compression turned on

### Execution results ordered by ascending serialization time
| Method  | Time   | Size |
|---|---|---|
| JsonSerialization2(compressed : false)  |  00:00:00.2288952 | 19614 |
| Protobuf  |  00:00:00.3844346 | 19539 |
| JsonSerialization  | 00:00:00.5124801  | 19614 |
| JsonSerialization2(compressed: true)  |  00:00:02.1728015 | 7217 |
| ProtobufZip  |  00:00:03.3699600 |  7221 |

### Results ordered by ascending serialization size
| Method  | Time   | Size |
|---|---|---|
| JsonSerialization2(compressed: true)  |  00:00:02.1728015 | 7217 |
| ProtobufZip  |  00:00:03.3699600 |  7221 |
| Protobuf  |  00:00:00.3844346 | 19539 |
| JsonSerialization2(compressed : false)  |  00:00:00.2288952 | 19614 |
| JsonSerialization  | 00:00:00.5124801  | 19614 |

Notice that:
- for uncompressed results, `JsonSerialization2(compressed : false) ` is faster than `ProtoBufSerialization` and faster than the original `JsonSerialization`.
- for compressed results, 'JsonSerialization2(compressed: true)' is faster and generates a more compact output than `ProtoBufZipSerialization`.

Of course, as far as uncompressed size is concerned, `ProtoBufSerialization` has the advantage since it's by definition a more compact output. But this advantage dwindles as the content size increases with respect to the size of the property names.

Still, the advantage is that it uses `System.Text.Json`, which is now part of .NET and has seen many performance improvements.

**Comment by GFlisch** [comment]
Merge to master
