### ISSUE TITLE
(Bug) Guidance 2022.2.1.9 17/10/2022: Incorrect Blazor registration

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#52]
When you create a Blazor front-end, a new registration section is added to the [Solution].Adfs.[Environment].json file.
For example:

~~~json
      {
        "nativeAppDisplayName": "HappyFlow Blazor Blazor Client",
        "redirectUri": "https://localhost:7062/",
        "identifier": "8230668f-a18d-4696-af75-06200088626d",
        "settings": "OAuth2.Blazor.Settings"
      }
~~~

The redirectUri is incorrect: it should be the actual internal redirect endpoint for the blazor app, e.g. `https://localhost:7062/authentication/login-callback`

For other environments, it should perhaps be clearer to write `https://your blazor endpoint/authentication/login-callback` to make it clear that the CORS endpoint doesn't have the last 2 segments.

**Comment by GFlisch** [comment]
Fixed.
