### ISSUE TITLE
(Bug) Guidance 2022.2.1.9 17/10/2022:  AboutVM.cs in a WPF does not compile / Missing Proxy generation.

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#55]
After generating a Wpf project, the AboutVM.cs has several issues
![AboutVM](https://user-images.githubusercontent.com/66954369/196636538-3c532849-b1d4-4140-aca2-f5f94a1d0f41.PNG)

These issues are because:
- A project reference to [Solution].Yarp.Facade.Sdk is missing in the Wpf project dependencies.
- The `HappyFlowYarpEnvironmentFacade` proxy has not been generated for the project.

**Comment by GFlisch** [comment]
Link to the fact the environment Sdk was not generated => A popup will warn the user to first build the Yarp project...
