### ISSUE TITLE
(Bug) Guidance 2022.2.1.9 17/10/2022: Include the solution name in the WPF application name just like in other registrations

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#58]
When you generate a WPF client, the registration in Json will look like this:

~~~json
      {
        "nativeAppDisplayName": "Wpf Wpf Client",
        "redirectUri": "http://localhost",
        "identifier": "a3bd9e4e-b9c9-4399-bc9c-5734a773804e",
        "settings": "WPF.Wpf.Settings"
      }
~~~

The fist "Wpf" in the `nativeAppDisplayName` should be changed to the solution name, like it's now the case for Blazor and basic authentication registration,  i.e.:

~~~json
        "nativeAppDisplayName": "SolutionName Wpf Client",
~~~

This has been upgraded to **_Bug_**, because the application name must be unique among all clients.
Registering the script with "Wpf Wpf Client" gives the following error:

> MSIS7605: The name of the client must be unique across all clients.

**Comment by GFlisch** [comment]
Fix with the new version

**Comment by GFlisch** [comment]
Fixed
