### ISSUE TITLE
(Improvement, Documentation) Guidance 2022.2.1.9 17/10/2022:  Explain how to get rid of the bad health endpoints in services

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#59]
When you generate a service, the Dapr configuration will be included by default:

~~~json
  "DaprSidekick": {
    "RuntimeDirectory": ".",
    "InitialDirectory": "C:\\PRJ\\Dapr",
    "SideCar": {
      "AppSsl": true
    }
  }
~~~

This will configure Dapr, even though C:\PRJ\Dapr may not exist or not configured correctly.
The result is that the console of the service will issue "bad health" on its service endpoint, even though nothing is the matter:

> [12:56:57 Serilog.AspNetCore.RequestLoggingMiddleware [Error] HTTP "GET" "/service/healthz" responded 503 in 12.1391 ms

We should document that developers can remove the `DaprSidekick` section to avoid these bad results.

Another option would be for the guidance to generate something like this:

~~~json
  /* Remove the "Disabled_" from the following section to enable Daps. See https://github.com/man-group/dapr-sidekick-dotnet for more details */
  "Disabled_DaprSidekick": {
    "RuntimeDirectory": ".",
    "InitialDirectory": "C:\\PRJ\\Dapr",
    "SideCar": {
      "AppSsl": true
    }
  },
~~~

**Comment by GFlisch** [comment]
As it is a configuration from the template and specific for each customer. I have removed this from the Template => so next trial, the Dapr config will be not there.
