### ISSUE TITLE
(Improvement) Guidance 2022.2.1.9 17/10/2022:  Reduce the probability of Blazor "double load" at initial startup.

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#62]
When a Blazor application is started for the very first time, it is reloaded after authentication when setting the language of the application to the language of the authenticated principal.
This is confusing for the user: the application starts, SSO authentication is performed, the home page is displayed and then the browser window goes blank, and the home page is shown again. Especially for complex applications, this is very noticable.

This reload is the instruction `_navigation.NavigateTo("", true);` located in the Guidance-generated `ClaimsPrincipalFactory` of the Blazor application:

~~~csharp
                    // set the current culture on the principal!
                    try
                    {
                        _logger.Technical().Debug($"No culture is set in the local storage. Reload with the new culture: {principal.Profile.Culture.Name}").Log();
                        await _localStorage.SetItemAsStringAsync("uiculture", principal.Profile.Culture.Name);

                        _navigation.NavigateTo("", true); // force reload to set the current culture!
                    }
                    catch (Exception ex)
                    {
                        _logger.Technical().Exception(ex).Log();
                    }
~~~

This only happens the first time the application is started in a browser that has not yet set its `uiculture` variable in local storage.

We cannot completely eliminate this behavior, but we can reduce its occurrence by observing that many users have their browser language set to the same language as specified in their principal. If this is the case, there's no point in reloading the application since the language is the same.

To do this, we need to change the above code in `ClaimsPrincipalFactory` as follows:

~~~csharp
                    // set the current culture on the principal!
                    try
                    {
                        _logger.Technical().Debug($"No culture is set in the local storage. Reload with the new culture: {principal.Profile.Culture.Name}").Log();
                        await _localStorage.SetItemAsStringAsync("uiculture", principal.Profile.Culture.Name);

                        var currentCulture = principal.Profile.CurrentCulture;
                        if (!((CultureInfo.DefaultThreadCurrentCulture?.Equals(currentCulture) ?? false) && (CultureInfo.DefaultThreadCurrentUICulture?.Equals(currentCulture) ?? false)))
                             _navigation.NavigateTo("", true); // force reload to set the current culture!
                    }
                    catch (Exception ex)
                    {
                        _logger.Technical().Exception(ex).Log();
                    }
~~~

This change checks if the current culture of the principal is the same as the Thread Culture/UICulture. The redirect is only performed when there's a difference.

In Blazor WebAssembly, the `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture` are not set. We therefore need to set them explicitly before we run the host.

To do this, add the following code in Program.cs between the call to `builder.Build()` and the call to `host.SetDefaultCulture` (the position is important!):

~~~csharp
var host = builder.Build();

// set the default current/currentUI culture to the first configured language of the browser.
// the aim is to avoid reloading the application if the language of the user matches the language of the browser (which will often be the case)
var jsRuntime = host.Services.GetRequiredService<IJSRuntime>();
var language = await jsRuntime.InvokeAsync<string>("defaultLocalisation");
if(!string.IsNullOrEmpty(language))
{
	// Some languages are "neutral" and don't specify a subculture. We don't have neutral language settings for users, only RFC 4646 compliant definitions, so we derive the ISO 3166 subculture from it.
	if (!language.Contains('-'))
		language += '-' + language.ToUpperInvariant();
	var defaultCultureInfo= CultureInfo.GetCultureInfo(language);
	CultureInfo.DefaultThreadCurrentCulture = defaultCultureInfo;
	CultureInfo.DefaultThreadCurrentUICulture = defaultCultureInfo;

}
await host.SetDefaultCulture();
~~~

The final piece of the puzzle is a bit JavaScript code to return the preferred browser language.
This can be added to the `index.html` page right after the Nova "dark theme" selector:

~~~javascript
        window.defaultLocalisation = () => {
            return navigator.languages && navigator.languages.length ? navigator.languages[0] : navigator['userLanguage']
                || navigator.language
                || navigator['browserLanguage']
                || 'en-US';
        };
~~~

With these changes, when the language of the browser matches the language of the user, no reload will occur.

Note: some browsers (incldung Edge) allow "neutral" languages to be specified (i.e., without a subculture). These languages have names like "fr" or "nl". However, culture information in the user database do not omit the subculture. Therefore, the browser languages that are neutral are completed with a subculture derived from the language: "fr" becomes "fr-FR", "nl" becomes "nl-NL". 
In some cases, this will not match: some users have "nl-NL", but others have "nl-BE". There is no solution, but in these cases page reload will occur.
We could ignore the subculture in Blazor, but we would be losing information and also be ignoring the browser language that have their subculture defined.

**Comment by rdarko** [comment]
fixed
