### ISSUE TITLE
(Bug) Guidance 2022.2.1.9 20/10/2022: Configuration of OAuth in appsettings for WPF has a different name

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#66]
The appsettings contains:

~~~json
  "WPF.OAuth2.Wpf.Settings": {...}
~~~

But the TokenSettings reader accesses `OAuth2.Wpf.Settings`:

~~~csharp
    public TokenSettings(IConfiguration configuration) : base("OAuth2.Wpf.Settings", configuration)
~~~

**Comment by GFlisch** [comment]
Have redeployed the template but was fixed for me

**Comment by GFlisch** [comment]
Fix by template => I have also integrate more

    if (!IsInvokedByNSwag())
	{
        app.MapGrpcReflectionService();
        app.MapHealthChecksUI();
        app.MapReverseProxy();
	}
