### ISSUE TITLE
(Bug) Typo in data layer generated code

### ISSUE THREAD

**Issue by fcc753** [GFlisch/Arc4u.Guidance.Doc#67]
DBSet names are suffixed with 2 ss instead of just 1.

for FooData entity the DBSet is named *FooDatass* in the declaration, but it is referenced as *FooDatas*.

**Comment by GFlisch** [comment]
Hi @fcc753 ,

Is it still the case with the Guidance 2022.2.1.9? In theory this bug has been fixed.

Can you check?

Thanks,

Gilles

**Comment by fcc753** [comment]
I did check. The two s' are gone.  But now another issue comes up.  I created an entity named FooEntity.  

DBSet is named as expected **FooEntities** but references to it elsewhere are of the form FooEntitys ;-(

**Comment by GFlisch** [comment]
Fixed. Will be released in the version 2022.1.10.
Thanks @fcc753.
