### ISSUE TITLE
Make arc4u OWASP compliant 

### ISSUE THREAD

**Issue by rdarko** [GFlisch/Arc4u.Guidance.Doc#91]
Check the OWASP.org additional infos

copied from https://github.com/GFlisch/Arc4u/projects/1#card-83600346

**Comment by HaGGi13** [comment]
@GFlisch and I integrated the OWASP Dependency Check by a dedicated [build pipeline](https://github.com/GFlisch/Arc4u/actions/workflows/Owasp.yml).
So there are reports by now that list may existing vulnerabilities.
