### ISSUE TITLE
Can not add existing domain model to database project 

### ISSUE THREAD

**Issue by janschmidmaier50** [GFlisch/Arc4u.Guidance.Doc#99]
If one creates a domain object before creating a database project, it seems, that it is not possible to create a datalayer for that existing domain object.
![image](https://user-images.githubusercontent.com/114572200/213169633-3f1a75db-3119-40f7-8f46-880d8d79a746.png)
(remark: Book (domain object), BookBL are existing, BookDL **not**

Clicking on "Add from an existing entity business classes" that opens a window with an empty class selection, although I would excpect `BookBL` or `Book` be selectable.
![image](https://user-images.githubusercontent.com/114572200/213170494-77585c66-925e-4f5a-83d0-22159af125c2.png)

The text of the context menu should be about 'entity' **or** 'business', because those describe different things. 
Also it should be called 'class' instead of 'classes'

**Comment by rdarko** [comment]
this has been fixed, thanks Jan
